services:
  redis:
    build: ./Redis
    ports:
      - "6378:6379"
  
  user-backend:
    build: ./src
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app
      #- /app/node_modules