services:
  redis:
    build: ./Redis
    ports:
      - "6378:6378"
    networks:
      - net

  prometheus:
    build: ./Prometheus
    ports:
      - "9090:9090"
    depends_on:
      - user-backend
    networks:
      - net
  
  user-backend:
    build: ./src/User-Friends
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/User-Friends:/app
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - net

  chat-backend:
    build: ./src/Chat
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/Chat:/app
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - net

networks:
  net: