services:
  redis:
    build: ./Redis
    ports:
      - "6378:6378"
    networks:
      - net

  #prometheus:
  #  build: ./Prometheus
  #  ports:
  #    - "9090:9090"
  #  depends_on:
  #    - user-backend
  #  networks:
  #    - net
  #
  #grafana:
  #  image: grafana/grafana-enterprise
  #  container_name: grafana
  #  restart: unless-stopped
  #  ports:
  #   - '3000:3000'
  #  networks:
  #    - net
  #
  #node_exporter:
  #  image: quay.io/prometheus/node-exporter:latest
  #  container_name: node_exporter
  #  command:
  #    - '--path.rootfs=/host'
  #  pid: host
  #  restart: unless-stopped
  #  volumes:
  #    - '/:/host:ro,rslave'
  #  networks:
  #    - net
  
  user-backend:
    build: ./src/User-Friends
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/User-Friends:/app
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - net

  chat-backend:
    build: ./src/Chat
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src/Chat:/app
      - /app/node_modules
    depends_on:
      - redis
    networks:
      - net
  
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - chat-backend
      - user-backend
    volumes:
      - ./src/Frontend:/usr/share/nginx/html
    networks:
      - net

networks:
  net: