global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: UserFriends
    static_configs:
      - targets: ['user-backend:8080']
  - job_name: node
    static_configs:
      - targets: ['node_exporter:9100']
